# Generated by Django 4.2.11 on 2024-03-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='URL')),
                ('category_priority', models.PositiveSmallIntegerField()),
                ('category_whenCreated', models.DateTimeField(auto_now_add=True)),
                ('category_visible', models.BooleanField(default=True)),
                ('category_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_tag', models.CharField(max_length=64)),
                ('section', models.PositiveSmallIntegerField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('whenCreated', models.DateTimeField(auto_now_add=True)),
                ('tip_visible', models.BooleanField(default=True)),
                ('dimension', models.PositiveSmallIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sheet.tipscategory')),
            ],
        ),
    ]
